/* ja-names.js
 * Japanese item name dictionary for stardew-predictor, generated from the game's own
 * localization files (Content/Strings/{Objects,BigCraftables,Furniture,Weapons,Tools,
 * EnchantmentNames,Shirts,Pants}.xnb joined with their .ja-JP.xnb counterparts on the
 * string key; Stardew Valley 1.6.15). Keys are English display names as used by the
 * predictor's item tables, values are the official Japanese display names.
 * Regenerate by unpacking those XNB pairs (e.g. with LeonBlade/xnbcli) and re-joining.
 */
var JA_NAMES = {
"\"Good Grief\" Shirt": "「やれやれ」シャツ",
"'1000 Years From Now'": "「1000年後」",
"'A Night On Eco-Hill'": "「エコーヒルの夜」",
"'Abstract'": "「抽象」",
"'Binary'": "「バイナリ」",
"'Blue City'": "「ブルーシティ」",
"'Blueberries'": "「ブルーベリー」",
"'Boat'": "「船」",
"'Burnt Offering'": "「焼け焦げた供物」",
"'Checkers'": "「チェッカー」",
"'Clouds'": "「雲々」",
"'Community Center'": "「公民館」",
"'Dancing Grass'": "「踊る草原」",
"'Frozen Dreams'": "「氷の夢」",
"'Groovy'": "「グルーヴィー」",
"'Highway 89'": "「ハイウェイ89」",
"'Hut'": "「小屋」",
"'It Howls In The Rain'": "「雨の中での遠吠え」",
"'Jade Hills Extended'": "「翡翠の丘」（大）",
"'Jade Hills'": "「翡翠の丘」",
"'Journey Of The Prairie King: The Motion Picture'": "「大草原の王の旅：映画」",
"'Kitemaster '95'": "「カイトマスター '95」",
"'Land Of Clay'": "「土くれの地」",
"'Little Buddies'": "「小さな仲間たち」",
"'Little Tree'": "「小さな木」",
"'Mysterium'": "「ミステリアム」",
"'Natural Wonders: Exploring Our Vibrant World'": "「自然の不思議：私たちの活気に満ちた世界を探る」",
"'Pathways'": "「通路」",
"'Physics 101'": "「物理学101」",
"'Portrait Of A Mermaid'": "「人魚の肖像画」",
"'Primal Motion'": "「原発の挙止」",
"'Queen of the Gem Sea'": "「ジェム海の女王」",
"'Red Eagle'": "「赤いワシ」",
"'Runes'": "「ルーン文字」",
"'Solar Kingdom'": "「太陽の王国」",
"'Spires'": "「尖塔」",
"'Squid Kid'": "「イカちゃん」",
"'Stardrop'": "「スタードロップ」",
"'Starship'": "「宇宙船」",
"'Sun #44'": "「太陽44番」",
"'Sun #45'": "「太陽45番」",
"'The Brave Little Sapling'": "「勇敢な小さな苗木」",
"'The Miracle At Coldstar Ranch'": "「コールドスター牧場での奇跡」",
"'The Muzzamaroo'": "「ムツァマルー」",
"'The Serpent'": "「蛇」",
"'The Zuzu City Express'": "「ズズシティエクスプレス」",
"'Three Trees'": "「三本の樹」",
"'Tropical Fish #173'": "「熱帯魚 #173」",
"'UFO'": "「UFO」",
"'VGA Paradise'": "「VGAパラダイス」",
"'Vanilla Villa'": "「白い邸宅」",
"'Vista'": "「風景」",
"'Void Swirls'": "「ヴォイドの渦」",
"'Volcano' Photo": "「火山」の写真",
"'Wizard's Tower'": "「魔術師の塔」",
"'Wumbus'": "「ウンバス」",
"80's Shirt (F)": "80年代のシャツ（女）",
"80's Shirt (M)": "80年代のシャツ（男）",
"???": "???",
"??Foroguemon??": "??フロッグモン??",
"??HMTGF??": "??HMTGF??",
"??Pinky Lemon??": "??ピンキーレモン??",
"A package of gourmet mushrooms.": "グルメなキノコの一品。",
"A whole fish, smoked to perfection.": "魚を丸一匹くんせいにしたもの。",
"Abby's Planchette": "アビゲイルの占い板",
"Abigail Portrait": "アビゲイルのポートレート",
"Acorn": "ドングリ",
"Advanced Iridium Rod": "改良型イリジウムの釣竿",
"Advanced TV Remote": "高機能テレビリモコン",
"Aerinite": "エリナイト",
"Aged Roe": "熟成卵",
"Alamite": "アラマイト",
"Albacore": "ビンナガ",
"Alex Portrait": "アレックスのポートレート",
"Alex's Bat": "アレックスのバット",
"Algae Soup": "藻のスープ",
"Aluminum Can": "アルミ缶",
"Amaranth": "アマランサス",
"Amaranth Seeds": "アマランサスのタネ",
"Amethyst": "アメシスト",
"Amethyst Crystal Ball": "アメシストの水晶玉",
"Amethyst Ring": "アメシストの指輪",
"Amethyst Stone": "アメシスト鉱脈",
"Amphibian Fossil": "両生類の化石",
"Anchor": "いかり",
"Anchovy": "カタクチイワシ",
"Ancient Doll": "古代の人形",
"Ancient Drum": "古代の太鼓",
"Ancient Fruit": "古代のフルーツ",
"Ancient Seed": "古代のタネ",
"Ancient Seeds": "古代のタネ",
"Ancient Stool": "とても古いスツール",
"Ancient Sword": "古代のつるぎ",
"Ancient Table": "とても古いテーブル",
"Angler": "ツリビトアンコウ",
"Animal Catalogue": "動物カタログ",
"Antiquity Shirt": "アンティークシャツ",
"Anvil": "カナトコ",
"Apple": "リンゴ",
"Apple Sapling": "リンゴの苗",
"Apricot": "アプリコット",
"Apricot Sapling": "アプリコットの苗",
"Aquamarine": "アクアマリン",
"Aquamarine Crystal Ball": "アクアマリンの水晶玉",
"Aquamarine Ring": "アクアマリンの指輪",
"Aquamarine Shirt": "アクアマリンシャツ",
"Aquamarine Stone": "アクアマリン鉱脈",
"Aquatic Sanctuary": "水の聖域",
"Arcane Shirt": "秘儀のシャツ",
"Archaeologist": "考古学者",
"Arctic Shard": "北極のかけら",
"Arrowhead": "矢じり",
"Art Photo": "芸術的な写真",
"Art Photo 2": "芸術的な写真2",
"Artful": "技巧派",
"Artichoke": "アーティチョーク",
"Artichoke Dip": "アーティチョークディップ",
"Artichoke Seeds": "アーティチョークのタネ",
"Artifact Spot": "発掘ポイント",
"Artifact Trove": "アーティファクト・トロヴ",
"Artist Bookcase": "アートな本棚",
"Auto-Grabber": "自動収穫機",
"Auto-Hook": "自動引き上げ",
"Auto-Petter": "自動ナデナデ装置",
"Autumn's Bounty": "秋のめぐみ",
"Axe": "オノ",
"Backpack Shirt": "バックパックシャツ",
"Baggy Pants": "バギーパンツ",
"Bait": "釣りエサ",
"Bait And Bobber": "エサとウキ",
"Bait Maker": "エサ製造器",
"Baked Fish": "焼き魚",
"Bamboo Mat": "竹マット",
"Bamboo Pole": "竹の釣竿",
"Banana": "バナナ",
"Banana Pudding": "バナナプリン",
"Banana Sapling": "バナナの苗",
"Banana Shirt": "バナナシャツ",
"Bandana Shirt": "バンダナシャツ",
"Barbed Hook": "かえし針",
"Barrel": "タル",
"Barrel Brazier": "タルのたき火台",
"Baryte": "重晶石",
"Basalt": "玄武岩",
"Basic Fertilizer": "きほんの肥料",
"Basic Log": "丸太",
"Basic Pullover (F)": "ベーシックプルオーバー（女）",
"Basic Pullover (M)": "ベーシックプルオーバー（男）",
"Basic Retaining Soil": "きほんの保水土",
"Basic Window": "ふつうの窓",
"Bat Wing": "コウモリのつばさ",
"Battery Pack": "電池",
"Bean Hotpot": "マメのシチュー",
"Bean Starter": "サヤエンドウ栽培セット",
"Bear Statue": "クマの像",
"Bear's Knowledge": "クマのちえ",
"Bed": "ベッド",
"Bee House": "ハチの巣箱",
"Beer": "ビール",
"Beet": "ビーツ",
"Beet Seeds": "ビーツのタネ",
"Belted Coat": "ベルト付きコート",
"Berry Basket": "ベリーつみのカゴ",
"Big Chest": "大きな箱",
"Big Green Cane": "グリーンステッキ（大）",
"Big Red Cane": "レッドステッキ（大）",
"Big Stone Chest": "大きな石の箱",
"Bikini Top": "ビキニトップ",
"Birch Bench": "バーチ材のベンチ",
"Birch Chair": "バーチ材のイス",
"Birch Double Bed": "カバノキのダブルベッド",
"Birch Dresser": "バーチ材のタンス",
"Birch End Table": "バーチ材のサイドテーブル",
"Birch Lamp End Table": "バーチ材のランプのサイドテーブル",
"Birch Table": "バーチ材のテーブル",
"Birch Tea-Table": "バーチ材のティーテーブル",
"Bird House": "鳥小屋",
"Bixite": "ビキサイト",
"Black Cushion": "黒いクッション",
"Black Leather Jacket": "ブラックレザージャケット",
"Blackberry": "ブラックベリー",
"Blackberry Cobbler": "ブラックベリーパイ",
"Blacksmith Apron": "鍛冶屋のエプロン",
"Blobfish": "ぶくぶく魚",
"Blossom Rug": "フラワーラグマット",
"Blue Armchair": "ブルーのひじかけイス",
"Blue Book": "青い本",
"Blue Bottle": "青いボトル",
"Blue Buttoned Vest": "ブルーボタン付きベスト",
"Blue Couch": "ブルーソファ",
"Blue Cushion": "青いクッション",
"Blue Diner Chair": "青いダイナーチェア",
"Blue Discus": "ブルーディスカス",
"Blue Grass Starter": "青葉栽培キット",
"Blue Hoodie": "ブルーのパーカー",
"Blue Jazz": "ブルージャズ",
"Blue Long Vest": "ブルーロングベスト",
"Blue Pinstripe Bed": "青いピンストライプのベッド",
"Blue Pinstripe Double Bed": "青いピンストライプのダブルベッド",
"Blue Sleeping Junimo": "青い眠ったジュニモ",
"Blue Slime Egg": "ブルースライムのタマゴ",
"Blue Stool": "青いスツール",
"Blueberry": "ブルーベリー",
"Blueberry Seeds": "ブルーベリーのタネ",
"Blueberry Tart": "ブルーベリータルト",
"Boarded Window": "板で塞がれた窓",
"Bobo Shirt": "ボボシャツ",
"Bobo Statue": "ボボ像",
"Bok Choy": "チンゲンサイ",
"Bok Choy Seeds": "チンゲンサイのタネ",
"Bomb": "ボム",
"Bomber Jacket": "ボンバージャケット",
"Bone Flute": "ホネの笛",
"Bone Fragment": "骨の破片",
"Bone Mill": "骨粉砕機",
"Bone Rug": "骨のラグ",
"Bone Sword": "ホネの剣",
"Bonfire": "たき火",
"Bongo": "ボンゴ",
"Bonsai Tree": "ぼんさい",
"Book Of Stars": "星の本",
"Book Pile": "本の山",
"Book Stack": "本の積み重ね",
"Book of Mysteries": "ミステリーの本",
"Bookcase": "本棚",
"Bottomless": "底なし",
"Boulder": "巨岩",
"Bountiful Dining Table": "豪華なダイニングテーブル",
"Bouquet": "花束",
"Box Lamp": "ボックスランプ",
"Bread": "パン",
"Breakfast Chair": "ブレックファーストチェア",
"Bream": "ブリーム",
"Brick Fireplace": "レンガの暖炉",
"Brick Floor": "レンガの床",
"Bridal Shirt": "ブライダルシャツ",
"Broccoli": "ブロッコリー",
"Broccoli Seeds": "ブロッコリーのタネ",
"Brochure Cabinet": "パンフレットのキャビネット",
"Broken CD": "割れたCD",
"Broken Glasses": "こわれたメガネ",
"Broken Television": "壊れたテレビ",
"Broken Trident": "欠けたトライデント",
"Brown Armchair": "ブラウンのひじかけイス",
"Brown Book": "茶色い本",
"Brown Couch": "ブラウンソファ",
"Brown Cushion": "茶色いクッション",
"Brown Jacket": "ブラウンジャケット",
"Brown Overalls": "ブラウンオーバーオール",
"Brown Suit": "ブラウンスーツ",
"Bruschetta": "ブルスケッタ",
"Budget TV": "箱型TV",
"Bug Killer": "虫キラー",
"Bug Meat": "虫の肉",
"Bug Steak": "虫のステーキ",
"Bulletin Board": "掲示板",
"Bullhead": "ブルヘッド",
"Burger Shirt": "バーガーシャツ",
"Burglar's Ring": "盗人の指輪",
"Burglar's Shank": "盗人のナイフ",
"Buried Tire": "埋まったタイヤ",
"Burlap Rug": "黄麻布ラグ",
"Butterfly Hutch": "バタフライハッチ",
"Butterfly Powder": "蝶のパウダー",
"Button Down Shirt": "ボタンダウンシャツ",
"CCFishTank": "公民館の水槽",
"Cactus": "サボテン",
"Cactus Fruit": "サボテンフルーツ",
"Cactus Seeds": "サボテンのタネ",
"Calcite": "カルサイト",
"Calendar": "カレンダー",
"Calico Egg": "カリコエッグ",
"Calico Egg Stone": "カリコエッグストーン",
"Calico Falls": "カリコの滝",
"Calico Statue": "カリコの像",
"Camera": "カメラ",
"Camo Shirt": "カモシャツ",
"Campfire": "キャンプファイア",
"Camping Stove": "キャンプ用コンロ",
"Candle Lamp": "キャンドルランプ",
"Candy Table": "キャンディ柄のテーブル",
"Canvas Jacket": "キャンバスジャケット",
"Captain's Uniform": "船長のユニフォーム",
"Cardigan": "カーディガン",
"Carp": "コイ",
"Carp Shirt": "カープシャツ",
"Carp Surprise": "コイのびっくり揚げ",
"Carrot": "ニンジン",
"Carrot Seeds": "ニンジンのタネ",
"Carved Brazier": "木彫りのたき火台",
"Carved Window": "彫刻窓",
"Carving Knife": "肉切りナイフ",
"Cash Register": "会計レジ",
"Cask": "熟成ダル",
"Cat Tree": "キャットツリー",
"Catalogue": "カタログ",
"Catfish": "ナマズ",
"Cauldron": "大釜",
"Cauliflower": "カリフラワー",
"Cauliflower Seeds": "カリフラワーのタネ",
"Cave Carrot": "洞窟ニンジン",
"Cave Jelly": "洞窟ゼリー",
"Caveman Shirt": "ケイヴマンシャツ",
"Caviar": "キャビア",
"Ceiling Flags": "天井用の旗",
"Ceiling Leaves": "つる植物のステッカー",
"Celestine": "セレスタイン",
"Ceramic Pillar": "陶器の柱",
"Challenge Bait": "チャレンジ釣りエサ",
"Chanterelle": "アンズタケ",
"Charcoal Kiln": "炭焼き窯",
"Cheese": "チーズ",
"Cheese Cauliflower": "カリフラワーのチーズ焼き",
"Cheese Press": "チーズプレス",
"Chef Coat": "シェフコート",
"Cherry": "サクランボ",
"Cherry Bomb": "チェリーボム",
"Cherry Sapling": "サクランボの苗",
"Chest": "箱",
"Chewing Stick": "歯みがき棒",
"Chewy pieces of dried fruit.": "歯ごたえのあるドライフルーツ。",
"Chicken Decal": "ニワトリのステッカー",
"Chicken Statue": "ニワトリの像",
"Child Bed": "子供用ベッド",
"China Cabinet": "中華風キャビネット",
"Chipped Amphora": "割れたつぼ",
"Chocolate Cake": "チョコレートケーキ",
"Chowder": "クラムチャウダー",
"Chub": "チャブ",
"Cinder Shard": "噴石のかけら",
"Cinder Shard Stone": "噴石のかけら鉱脈",
"Circuitboard Shirt": "サーキットボードシャツ",
"Circular Junimo Rug": "円形のジュニモのラグ",
"Clam": "アサリ",
"Classic Lamp": "クラシックなランプ",
"Classic Overalls": "定番オーバーオール",
"Classy Top (F)": "上品なシャツ（女）",
"Classy Top (M)": "上品なシャツ（男）",
"Clay": "粘土",
"Clay Stone": "粘土鉱脈",
"Claymore": "クレイモア",
"Cloth": "布",
"Clothesline": "物干しロープ",
"Cloud Decal": "雲のステッカー",
"Clouds Banner": "雲のバナー",
"Coal": "石炭",
"Coat Stand": "コートスタンド",
"Cobblestone Path": "玉石の小道",
"Cockle": "ザルガイ",
"Coconut": "ココナッツ",
"Coffee": "コーヒー",
"Coffee Bean": "コーヒー豆",
"Coffee Maker": "コーヒーメーカー",
"Coffee Table": "コーヒーテーブル",
"Coleslaw": "コールスロー",
"Collared Shirt": "襟付きシャツ",
"Colorful Set": "カラフルなセット",
"Combat Quarterly": "季刊コンバット",
"Combined Ring": "組み合わせた指輪",
"Common Mushroom": "マッシュルーム",
"Complete Breakfast": "朝食セット",
"Cookies": "クッキー",
"Cookout Kit": "野外料理キット",
"Copper Axe": "銅のオノ",
"Copper Bar": "銅ののべ棒",
"Copper Breastplate": "銅製ブレストプレート",
"Copper Hoe": "銅のクワ",
"Copper Ore": "銅鉱石",
"Copper Pan": "銅の砂金皿",
"Copper Pickaxe": "銅のツルハシ",
"Copper Stone": "銅鉱脈",
"Copper Trash Can": "銅のゴミ箱",
"Copper Watering Can": "銅のジョウロ",
"Coral": "サンゴ",
"Cork Bobber": "コルクのウキ",
"Corn": "トウモロコシ",
"Corn Plant": "コーンプラント",
"Corn Seeds": "トウモロコシのタネ",
"Country Chair": "カントリーチェア",
"Country Lamp": "カントリーなランプ",
"Cow Decal": "ウシのステッカー",
"Cowboy Poncho": "カウボーイポンチョ",
"Crab": "カニ",
"Crab Cake Shirt": "カニケーキシャツ",
"Crab Cakes": "クラブケーキ",
"Crab Pot": "カニかご",
"Crabshell Ring": "クラブシェルリング",
"Cranberries": "クランベリー",
"Cranberry Candy": "クランベリーキャンディ",
"Cranberry Sauce": "クランベリーソース",
"Cranberry Seeds": "クランベリーのタネ",
"Crate": "木箱",
"Crayfish": "ザリガニ",
"Crimsonfish": "クリムゾンフィッシュ",
"Crispy Bass": "バスのサクサク揚げ",
"Crocus": "クロッカス",
"Crop Tank Top (F)": "クロップタンクトップ（女）",
"Crop Tank Top (M)": "クロップタンクトップ（男）",
"Crop Top Shirt": "クロップトップシャツ",
"Crusader": "クルセイダー",
"Crystal Ball": "水晶玉",
"Crystal Chair": "クリスタルのイス",
"Crystal Dagger": "クリスタルダガー",
"Crystal Floor": "クリスタルの床",
"Crystal Fruit": "クリスタルフルーツ",
"Crystal Path": "クリスタルの小道",
"Crystalarium": "結晶コピーマシン",
"Curiosity Lure": "気になるルアー",
"Curly Tree": "ねじれた木",
"Cursed P.K. Arcade System": "呪われたP.K. アーケードシステム",
"Cute Chair": "キュートなイス",
"Cutlass": "カットラス",
"Daffodil": "ラッパスイセン",
"Dandelion": "タンポポ",
"Dark Bandana Shirt": "ダークバンダナシャツ",
"Dark Bookcase": "ダークな本棚",
"Dark Cat Tree": "ダークなキャットツリー",
"Dark Couch": "ダークなソファ",
"Dark Doghouse": "ダークな犬小屋",
"Dark Highlight Shirt": "ダークハイライトシャツ",
"Dark Jacket": "ダークジャケット",
"Dark Junimo Cushion": "ダークなジュニモのクッション",
"Dark Leafy Wall Panel": "ダークな葉っぱの壁飾り",
"Dark Piano": "ダークピアノ",
"Dark Retro Cushion": "ダークでレトロなクッション",
"Dark Rug": "ダークなラグマット",
"Dark Shirt": "ダークシャツ",
"Dark Sign": "黒い掲示板",
"Dark Striped Shirt": "ダークストライプシャツ",
"Dark Sword": "闇の剣",
"Dark Table": "ダークなテーブル",
"Dark Talisman": "闇のタリスマン",
"Dark Throne": "ダークな玉座",
"Dark Wizard Cushion": "ダークな魔術師のクッション",
"Darkness Suit": "ダークネススーツ",
"Dead Tree": "デッドツリー",
"Deconstructor": "分解器",
"Decorative Axe": "飾りのオノ",
"Decorative Barrel": "装飾用のタル",
"Decorative Bowl": "はなやかなボウル",
"Decorative Door": "装飾用のドア",
"Decorative Hatch": "装飾用の出入り口",
"Decorative Joja Door": "装飾用のJojaのドア",
"Decorative Junimo Door": "装飾用のジュニモのドア",
"Decorative Lantern": "装飾用ランタン",
"Decorative Oak Ladder": "装飾用のオーク材のハシゴ",
"Decorative Pitcher": "はなやかな水差し",
"Decorative Pitchfork": "飾りのピッチフォーク",
"Decorative Pot": "飾りもののつぼ",
"Decorative Retro Door": "装飾用のレトロなドア",
"Decorative Shovel": "装飾用のシャベル",
"Decorative Spears": "装飾用ヤリ",
"Decorative Sword": "装飾用の剣",
"Decorative Trash Can": "飾りのゴミ箱",
"Decorative Walnut Ladder": "装飾用のクルミ材のハシゴ",
"Decorative Wizard Door": "装飾用の魔術師のドア",
"Dehydrator": "乾燥器",
"Deluxe Bait": "デラックス釣りエサ",
"Deluxe Fertilizer": "デラックス肥料",
"Deluxe Fish Tank": "豪華な水槽",
"Deluxe Red Double Bed": "豪華な赤いダブルベッド",
"Deluxe Retaining Soil": "デラックス保水土",
"Deluxe Scarecrow": "デラックスかかし。",
"Deluxe Speed-Gro": "グングンノビールデラックス",
"Deluxe Tree": "デラックスツリー",
"Deluxe Worm Bin": "デラックスミミズ飼育器",
"Denim Jacket": "デニムジャケット",
"Desert Chair": "砂漠のイス",
"Desert End Table": "砂漠のサイドテーブル",
"Desert Fireplace": "砂漠の暖炉",
"Desert Flags": "砂漠の旗",
"Desert Rug": "砂漠のラグ",
"Desert Table": "砂漠のテーブル",
"Diamond": "ダイヤモンド",
"Diamond Stone": "Dダイヤモンド鉱脈",
"Dining Chair": "ダイニングチェア",
"Dinosaur Egg": "恐竜のタマゴ",
"Dinosaur Mayonnaise": "恐竜マヨネーズ",
"Dinosaur Pants": "恐竜のパンツ",
"Dirt Shirt": "ダートシャツ",
"Dish O' The Sea": "おさかな定食",
"Diviner Table": "占い師のテーブル",
"Doghouse": "犬小屋",
"Doll Shirt": "ドールシャツ",
"Dolomite": "ドロマイト",
"Door": "ドア",
"Dorado": "ドラド",
"Double Bed": "ダブルベッド",
"Dragon Tooth": "ドラゴンの歯",
"Dragontooth Club": "ドラゴンの歯のこんぼう",
"Dragontooth Cutlass": "ドラゴンの歯のカットラス",
"Dragontooth Shiv": "ドラゴンの歯のナイフ",
"Dressed Spinner": "ドレススピナー",
"Dried": "乾物",
"Dried Fruit": "ドライフルーツ",
"Dried Mushrooms": "干しキノコ",
"Dried Starfish": "干からびたヒトデ",
"Dried Sunflowers": "ヒマワリのドライフラワー",
"Driftwood": "流木",
"Drum Block": "ドラムブロック",
"Duck Egg": "アヒルのタマゴ",
"Duck Feather": "アヒルのハネ",
"Duck Mayonnaise": "ダックマヨネーズ",
"Dusty Skull": "ほこりまみれのドクロ",
"Dwarf Dagger": "ドワーフのダガー",
"Dwarf Gadget": "ドワーフの装置",
"Dwarf Hammer": "ドワーフのハンマー",
"Dwarf Scroll I": "ドワーフの巻物 I",
"Dwarf Scroll II": "ドワーフの巻物 II",
"Dwarf Scroll III": "ドワーフの巻物 III",
"Dwarf Scroll IV": "ドワーフの巻物 IV",
"Dwarf Sword": "ドワーフの剣",
"Dwarvish Helm": "ドワーフのカブト",
"Dwarvish Safety Manual": "ドワーフの安全マニュアル",
"Dwarvish Translation Guide": "ドワーフ語翻訳ガイド",
"Earth Crystal": "アースクリスタル",
"Ectoplasm": "エクトプラズム",
"Eel": "ウナギ",
"Efficient": "効率的",
"Egg": "タマゴ",
"Eggplant": "ナス",
"Eggplant Parmesan": "ナスのチーズ焼き",
"Eggplant Seeds": "ナスのタネ",
"Elegant Fireplace": "エレガントな暖炉",
"Elegant Vase": "エレガントな花びん",
"Elf Blade": "エルフの剣",
"Elixir Bundle": "エリクサーのセット",
"Elixir Shelf": "エリクサーの棚",
"Elixir Table": "エリクサーのテーブル",
"Elliott Portrait": "エリオットのポートレート",
"Elliott's Pencil": "エリオットのえんぴつ",
"Elvish Jewelry": "エルフのアクセサリー",
"Emerald": "エメラルド",
"Emerald Crystal Ball": "エメラルドの水晶玉",
"Emerald Ring": "エメラルドの指輪",
"Emerald Stone": "エメラルド鉱脈",
"Emily Portrait": "エミリーのポートレート",
"Emily's Magic Shirt": "エミリーのマジックシャツ",
"Empty Capsule": "からっぽのカプセル",
"Energy Tonic": "エネルギードリンク",
"Enricher": "エンリッチ施肥装置",
"Escargot": "エスカルゴ",
"Esperite": "エスパーライト",
"Excavator Shirt": "ショベルシャツ",
"Exotic Double Bed": "エキゾチックなダブルベッド",
"Exotic Palace": "異国の宮殿",
"Exotic Tree": "エキゾチックな木",
"Explosive Ammo": "炸裂弾",
"Faded Denim Shirt": "色あせたデニムシャツ",
"Fairy Dust": "妖精の粉",
"Fairy Rose": "フェアリーローズ",
"Fairy Seeds": "フェアリーシード",
"Fairy Stone": "フェアリーストーン",
"Fake Muscles Shirt": "フェイクマッスルシャツ",
"Fall Seeds": "秋のタネつめあわせ",
"Fallen Blue Book": "落ちた青い本",
"Fallen Brown Book": "落ちた茶色い本",
"Fallen Green Book": "落ちた緑の本",
"Fallen Purple Book": "落ちた紫の本",
"Fallen Red Book": "落ちた赤い本",
"Fallen Yellow Book": "落ちた黄色い本",
"Fancy House Plant": "ファンシーな観葉植物",
"Fancy Red Blouse": "ファンシーレッドブラウス",
"Fancy Table": "高級なテーブル",
"Far Away Stone": "はるかな石",
"Farm Computer": "農場コンピューター",
"Farmer Pants": "ファーマーパンツ",
"Farmer's Lunch": "牧場主のランチ",
"Feed Hopper": "エサやり機",
"Femur": "大たい骨",
"Festive Dining Table": "祝祭用ダイニングテーブル",
"Fiber": "せんい",
"Fiber Seeds": "せんいのタネ",
"Fiberglass Rod": "ファイバーグラスの釣竿",
"Fiddlehead Fern": "フィドルヘッド",
"Fiddlehead Risotto": "フィドルヘッドのリゾット",
"Field Snack": "エネルギーバー",
"Fire Opal": "ファイアオパール",
"Fire Quartz": "ファイアクオーツ",
"Fireworks (Green)": "花火（緑）",
"Fireworks (Purple)": "花火（紫）",
"Fireworks (Red)": "花火（赤）",
"Fish Shirt": "フィッシュシャツ",
"Fish Smoker": "魚のくんせい器",
"Fish Stew": "魚のシチュー",
"Fish Taco": "フィッシュタコス",
"Fisher": "漁師",
"Fisher Double Bed": "漁師のダブルベッド",
"Fishing Vest": "フィッシングベスト",
"Flames Shirt": "フレームシャツ",
"Flannel Shirt": "ネルシャツ",
"Floor Divider L": "フロアの仕切り（左）",
"Floor Divider R": "フロアの仕切り（右）",
"Floor TV": "フロアTV",
"Flounder": "平らな魚",
"Fluffy Shirt": "ふわふわシャツ",
"Fluorapatite": "フルオロアパタイト",
"Flute Block": "フルートブロック",
"Foliage Print": "葉っぱの絵",
"Food Pet Bowl": "ペット用フードボウル",
"Forest Sword": "フォレストソード",
"Fossil Stone": "化石鉱脈",
"Fossilized Leg": "脚の化石",
"Fossilized Ribs": "肋骨の化石",
"Fossilized Skull": "頭がい骨の化石",
"Fossilized Spine": "脊椎骨の化石",
"Fossilized Tail": "尻尾の化石",
"Fried Calamari": "イカフライ",
"Fried Eel": "ウナギフライ",
"Fried Egg": "目玉焼き",
"Fried Egg Shirt": "目玉焼きシャツ",
"Fried Mushroom": "キノコいため",
"Friendship 101": "友達のつくり方",
"Fringed Vest": "フリンジ付きベスト",
"Frozen Geode": "フローズンジオード",
"Frozen Geode Stone": "フローズンジオード鉱脈",
"Frozen Tear": "イエティのなみだ",
"Fruit Salad": "フルーツサラダ",
"Fruit Salad Rug": "フルーツサラダラグ",
"Funky Rug": "ファンキーなラグマット",
"Furnace": "溶鉱炉",
"Furniture Catalogue": "家具カタログ",
"Futan Bear": "おふとんベア",
"Futan Rabbit": "ふたんラビット",
"Galaxy Dagger": "ギャラクシーダガー",
"Galaxy Hammer": "ギャラクシーハンマー",
"Galaxy Slingshot": "ギャラクシーパチンコ",
"Galaxy Soul": "ギャラクシーソウル",
"Galaxy Sword": "ギャラクシーソード",
"Garden Pot": "植木鉢",
"Garlic": "ニンニク",
"Garlic Seeds": "ニンニクのタネ",
"Gate": "ゲート",
"Gaudy Shirt": "ガウディシャツ",
"Gem Stone": "宝石鉱脈",
"Geminite": "ジェミニクリスタル",
"Generous": "いい土地",
"Genie Pants": "魔神のパンツ",
"Geode": "ジオード",
"Geode Crusher": "ジオード粉砕機",
"Geode Stone": "ジオード鉱脈",
"Ghost Crystal": "ゴーストクリスタル",
"Ghostfish": "ヒヨケウオ",
"Ginger": "ショウガ",
"Ginger Ale": "ジンジャーエール",
"Ginger Overalls": "ジンジャーオーバーオール",
"Glacierfish": "アイスフィッシュ",
"Glacierfish Jr.": "アイスフィッシュ・ジュニア",
"Glass Shards": "ガラスのかけら",
"Glazed Yams": "サツマイモのミツがけ",
"Globby Shirt": "グロビーシャツ",
"Globe": "地球儀",
"Glow Ring": "光の指輪",
"Glowstone Ring": "グロウストーンの指輪",
"Glyph": "象形文字",
"Goat Cheese": "ヤギのチーズ",
"Goat Milk": "ヤギのミルク",
"Goby": "ハゼ",
"Gold Axe": "金のオノ",
"Gold Bar": "金ののべ棒",
"Gold Brazier": "金のたき火台",
"Gold Breastplate": "ゴールド製ブレストプレート",
"Gold Coin": "ゴールドコイン",
"Gold Hoe": "金のクワ",
"Gold Ore": "金鉱石",
"Gold Pan": "金の砂金皿",
"Gold Pickaxe": "金のツルハシ",
"Gold Pillar": "金の柱",
"Gold Stone": "金鉱脈",
"Gold Trash Can": "金のゴミ箱",
"Gold Trimmed Shirt": "ゴールドトリムシャツ",
"Gold Watering Can": "金のジョウロ",
"Golden Animal Cracker": "金の動物ビスケット",
"Golden Bobber": "金色のウキ",
"Golden Coconut": "金のココナッツ",
"Golden Egg": "金のタマゴ",
"Golden Mask": "黄金のマスク",
"Golden Mystery Box": "金のミステリーボックス",
"Golden Pumpkin": "ゴールデンパンプキン",
"Golden Relic": "黄金のプレート",
"Golden Scythe": "ゴールデン鎌",
"Golden Shirt": "ゴールデンシャツ",
"Golden Tag": "金色のタグ",
"Golden Walnut": "金のクルミ",
"Goodnight Shirt": "グッドナイトシャツ",
"Gourmand Statue": "食いしん坊の像",
"Gourmet Tomato Salt": "グルメなトマト塩",
"Grandfather Clock": "大きな古時計",
"Grandmother End Table": "おばあちゃんのサイドテーブル",
"Granite": "花こう岩",
"Grape": "ブドウ",
"Grape Starter": "ブドウ栽培キット",
"Grass Skirt": "グラススカート",
"Grass Starter": "牧草栽培キット",
"Grave Stone": "墓石",
"Gravel Path": "砂利の小道",
"Gray Hoodie": "グレーのパーカー",
"Gray Joja Bookcase": "グレーのJajaの本棚",
"Gray Joja Coffee Table": "グレーのJojaのコーヒーテーブル",
"Gray Joja Cushion": "グレーのJojaのクッション",
"Gray Joja Dresser": "グレーのJajaのタンス",
"Gray Joja End Table": "グレーのJojaのサイドテーブル",
"Gray Sleeping Junimo": "グレーの眠ったジュニモ",
"Gray Suit": "グレースーツ",
"Gray Vest": "グレーベスト",
"Green Algae": "緑の藻",
"Green Armchair": "グリーンのひじかけイス",
"Green Bean": "サヤエンドウ",
"Green Belted Shirt": "グリーンベルトシャツ",
"Green Book": "緑の本",
"Green Bottle": "緑のボトル",
"Green Buttoned Vest": "グリーンボタン付きベスト",
"Green Canes": "グリーンステッキ（小）",
"Green Cottage Rug": "みどりのコテージラグマット",
"Green Couch": "グリーンソファ",
"Green Cushion": "緑のクッション",
"Green Flannel Shirt": "グリーンフランネルシャツ",
"Green Jacket Shirt": "グリーンジャケットシャツ",
"Green Office Stool": "グリーンのオフィススツール",
"Green Overalls": "グリーンオーバーオール",
"Green Plush Seat": "グリーンのふかふかシート",
"Green Rain Weeds": "グリーンレインのタネ",
"Green Serpent Statue": "緑の蛇の像",
"Green Sleeping Junimo": "緑の眠ったジュニモ",
"Green Slime Egg": "グリーンスライムのタマゴ",
"Green Stool": "緑のスツール",
"Green Tea": "緑茶",
"Green Thumb Shirt": "グリーンサムシャツ",
"Green Tunic": "グリーンチュニック",
"Green Vest": "グリーンベスト",
"Groovy Chair": "グルーヴィーなイス",
"Haley Portrait": "ヘイリーのポートレート",
"Haley's Iron": "ヘイリーのアイロン",
"Haley's Lost Bracelet": "ヘイリーがなくしたブレスレット",
"Halibut": "オヒョウ",
"Hanging Fish": "つるされた魚",
"Hanging Shield": "つりさげシールド",
"Happy Shirt": "ハッピーシャツ",
"Hardwood": "堅い木",
"Hardwood Fence": "堅い木の柵",
"Harvey Portrait": "ハーヴィーのポートレート",
"Harvey's Mallet": "ハーヴィーのマレット",
"Hashbrowns": "ハッシュドポテト",
"Hay": "ほし草",
"Haymaker": "ほし草作り",
"Hazelnut": "ヘーゼルナッツ",
"Heart Shirt": "ハートシャツ",
"Heater": "ヒーター",
"Heavy Furnace": "強力溶鉱炉",
"Heavy Tapper": "大型樹液採取器",
"Hedge": "生垣",
"Helvite": "ヘルバイト",
"Hematite": "ヘマタイト",
"Her roots grow very deep... she wouldn't be happy in there.": "その根は深きに広がる…そこはあまりに狭すぎるだろう。",
"Herring": "ニシン",
"High Heat Shirt": "ハイハートシャツ",
"High-Waisted Shirt": "ハイウエストシャツ",
"Hoe": "クワ",
"Holiday Shirt": "ホリデーシャツ",
"Holly": "ひいらぎ",
"Holy Blade": "聖なるつるぎ",
"Honey": "ハチミツ",
"Hopper": "ホッパー",
"Hops": "ホップ",
"Hops Starter": "ホップ栽培キット",
"Horse Flute": "馬のフルート",
"Horse: The Book": "馬読本",
"Hot Java Ring": "暑いジャワの指輪",
"Hot Pepper": "トウガラシ",
"Hot Pink Shirt": "ホットなピンクシャツ",
"House Plant": "観葉植物",
"Hyper Speed-Gro": "グングンノビールハイパー",
"Ice Cream": "アイスクリーム",
"Ice Crystal": "アイスクリスタル",
"Ice Pip": "アイスピップ",
"Icy Banner": "氷のバナー",
"Icy Rug": "氷のラグマット",
"Immunity Band": "イミュニティバンド",
"Incubator": "ふ卵器",
"Indoor Hanging Basket": "室内吊りバスケット",
"Indoor Palm": "室内用ヤシの木",
"Industrial Pipe": "工業用パイプ",
"Infinity Blade": "インフィニティブレード",
"Infinity Dagger": "インフィニティダガー",
"Infinity Gavel": "インフィニティガベル",
"Insect Head": "昆虫の大アゴ",
"Iridium Axe": "イリジウムのオノ",
"Iridium Band": "イリジウムバンド",
"Iridium Bar": "イリジウムののべ棒",
"Iridium Breastplate": "イリジウム製ブレストプレート",
"Iridium Energy Shirt": "イリジウムエネルギーシャツ",
"Iridium Fireplace": "イリジウムの暖炉",
"Iridium Hoe": "イリジウムのクワ",
"Iridium Krobus": "イリジウムのクロバス",
"Iridium Milk": "イリジウムのミルク",
"Iridium Needle": "イリジウムニードル",
"Iridium Ore": "イリジウム鉱石",
"Iridium Pan": "イリジウムの砂金皿",
"Iridium Pickaxe": "イリジウムのツルハシ",
"Iridium Rod": "イリジウムの釣竿",
"Iridium Scythe": "イリジウムのカマ",
"Iridium Sprinkler": "イリジウム製スプリンクラー",
"Iridium Stone": "イリジウム鉱脈",
"Iridium Trash Can": "イリジウムのゴミ箱",
"Iridium Watering Can": "イリジウムのジョウロ",
"Iron Bar": "鉄ののべ棒",
"Iron Dirk": "鉄のダガー",
"Iron Edge": "鉄の剣",
"Iron Fence": "鉄の柵",
"Iron Lamp-post": "鉄の街灯",
"Iron Ore": "鉄鉱石",
"Iron Stone": "鉄鉱脈",
"Island Bikini": "アイランドビキニ",
"Item Pedestal": "アイテム用の台座",
"J": "J",
"J. Cola Light": "Jojaコーラネオン",
"J. Light": "Jのライト",
"J. Painting": "Jの絵",
"Jack Be Nimble, Jack Be Thick": "ジャックはすばやくたくましく",
"Jack-O-Lantern": "ジャックオーランタン",
"Jade": "ヒスイ",
"Jade Ring": "ヒスイの指輪",
"Jade Stone": "ヒスイ鉱脈",
"Jagoite": "ジャゴイト",
"Jamborite": "ジャンボー石",
"Jasper": "ジャスパー",
"Jazz Seeds": "ジャズのタネ",
"Jelly": "ジャム",
"Jester Shirt": "ジェスターシャツ",
"Jewelry Shirt": "ジュエリーシャツ",
"Jewels Of The Sea": "海の宝石",
"Joja Bed": "Jojaのベッド",
"Joja Bookcase": "Jojaの本棚",
"Joja Chair": "Jojaのイス",
"Joja Coffee Table": "Jojaのコーヒーテーブル",
"Joja Cola": "Jojaコーラ",
"Joja Cola Cans": "Jojaコーラの缶",
"Joja Cola Fridge": "Jojaコーラの冷蔵庫",
"Joja Cola Ornament": "Jojaコーラの壁飾り",
"Joja Cola Painting": "Jojaコーラの絵",
"Joja Cola Tea Table": "Jojaコーラのティーテーブル",
"Joja Couch": "Jojaのソファ",
"Joja Crate": "Jajaのクレート",
"Joja Cushion": "Jojaのクッション",
"Joja Dresser": "Jajaのタンス",
"Joja End Table": "Jojaのサイドテーブル",
"Joja Fireplace": "Jojaの暖炉",
"Joja Furniture Catalogue": "Joja家具カタログ",
"Joja HQ Painting": "Joja本社の絵",
"Joja Lamp": "Jajaのランプ",
"Joja Rug": "Jojaのラグ",
"Joja Shopping Cart": "Jojaのショッピングカート",
"Joja Stool": "Jajaのスツール",
"Joja Table": "Jojaのテーブル",
"Joja Vault": "Jojaの金庫",
"Journal Scrap": "日記の切れ端",
"Juice": "ジュース",
"Jukebox Ring": "ジュークボックスの指輪",
"Jungle Decal": "ジャングルのステッカー",
"Jungle Tank": "ジャングルの水槽",
"Jungle Torch": "ジャングルトーチ",
"Junimo Bag": "ジュニモのバッグ",
"Junimo Bed": "ジュニモのベッド",
"Junimo Bookcase": "ジュニモの本棚",
"Junimo Bundle": "ジュニモの荷物",
"Junimo Catalogue": "ジュニモカタログ",
"Junimo Chair": "ジュニモのイス",
"Junimo Chest": "ジュニモの箱",
"Junimo Couch": "ジュニモのソファ",
"Junimo Cushion": "ジュニモのクッション",
"Junimo Dresser": "ジュニモのタンス",
"Junimo End Table": "ジュニモのサイドテーブル",
"Junimo Fireplace": "ジュニモの暖炉",
"Junimo Flower": "ジュニモの花",
"Junimo Hut": "ジュニモの小屋",
"Junimo Kart Arcade System": "ゲームマシン：ジュニモカート",
"Junimo Lamp": "ジュニモのランプ",
"Junimo Mat": "ジュニモのマット",
"Junimo Plant": "ジュニモの植物",
"Junimo Plaque": "ジュニモの額",
"Junimo Plush": "ジュニモ・プラッシュ",
"Junimo Pot": "ジュニモのつぼ",
"Junimo Rug": "ジュニモのラグ",
"Junimo Star": "ジュニモの星",
"Junimo Stool": "ジュニモのスツール",
"Junimo Table": "ジュニモのテーブル",
"Junimo Tea Table": "ジュニモのティーテーブル",
"Junimo Tree": "ジュニモの木",
"Junimo Wall Plaque": "ジュニモの壁掛け額",
"Kale": "ケール",
"Kale Seeds": "ケールのタネ",
"Keg": "醸造ダル",
"Kelp Shirt": "昆布シャツ",
"King Chair": "王様のイス",
"Krobus Portrait": "クロバスのポートレート",
"Kudgel": "カジェル",
"Kyanite": "藍晶石",
"L. Goat Milk": "おおきなヤギミルク",
"L. Light String": "大きなライトストリング",
"Lantern": "ランタン",
"Large Book Pile": "大きな本の山",
"Large Book Stack": "大きな本の積み重ね",
"Large Brown Couch": "長いブラウンソファ",
"Large Cottage Rug": "大きなコテージラグマット",
"Large Egg": "おおきなタマゴ",
"Large Fish Tank": "大きな水槽",
"Large Green Rug": "大きな緑色のラグマット",
"Large Joja Crate": "大きなJajaのクレート",
"Large Joja Rug": "大きなJajaのラグ",
"Large Junimo Hut": "大きなジュニモの小屋",
"Large Milk": "おおきなミルク",
"Large Red Rug": "大きい赤色ラグマット",
"Large Retro Rug": "大きいレトロなラグ",
"Large Wizard Bookcase": "大きな魔術師の本棚",
"Largemouth Bass": "ブラックバス",
"Lava Eel": "溶岩ウナギ",
"Lava Katana": "マグマ刀",
"Lawn Flamingo": "フラミンゴ",
"Lead Bobber": "鉛のおもり",
"Lead Rod": "鉛のロッド。",
"Leafy Top": "リーフィートップス",
"Leafy Wall Panel": "葉っぱの壁飾り",
"Leah Portrait": "リアのポートレート",
"Leah's Sculpture": "リアの彫刻",
"Leah's Whittler": "リアの万能ナイフ",
"Leek": "ポロネギ",
"Legend": "レジェンド",
"Legend II": "レジェンド2世",
"Lemon Stone": "レモンストーン",
"Letterman Jacket": "レターマンジャケット",
"Lg. Futan Bear": "ビッグおふとんベア",
"Life Elixir": "ライフエリクサー",
"Lifesaver": "救命浮き輪",
"Light Blue Shirt": "ライトブルーシャツ",
"Light Blue Striped Shirt": "ライトブルーストライプシャツ",
"Light Green Rug": "薄緑色のラグマット",
"Light Leafy Wall Panel": "明るい葉っぱの壁飾り",
"Light Switch": "照明スイッチ",
"Lightning Rod": "ひらい針",
"Lime Green Striped Shirt": "ライムグリーンストライプシャツ",
"Lime Green Tunic": "ライムグリーンチュニック",
"Limestone": "石灰岩",
"Lingcod": "リングコッド",
"Lionfish": "ミノカサゴ",
"Little Photos": "スナップ写真",
"Lobster": "ロブスター",
"Lobster Bisque": "ロブスターのビスク",
"Locked Door": "カギつきドア",
"Log Panel": "丸太の壁パネル",
"Log Section": "平丸太",
"Long Cactus": "ロングサボテン",
"Long Dress": "ロングドレス",
"Long Elixir Table": "長いエリクサーのテーブル",
"Long Palm": "ロングパーム",
"Loom": "織り機",
"Lost Axe": "落としもののオノ",
"Lost Book": "紛失図書",
"Luau Skirt": "ルアウスカート",
"Luau Table": "ルアウのテーブル",
"Lucky Lunch": "ラッキーランチ",
"Lucky Purple Shorts": "幸運のむらさきパンツ",
"Lucky Ring": "幸運の指輪",
"Lumber": "板材",
"Lunarite": "ルナライト",
"Luxury Bookcase": "豪華な本棚",
"Luxury Table": "豪華なテーブル",
"Magenta Shirt": "マゼンタシャツ",
"Magic Bait": "魔法のエサ",
"Magic Ink": "魔法のインク",
"Magic Rock Candy": "魔法のロックキャンディ",
"Magic Sprinkle Shirt": "魔法のスプリンクルシャツ",
"Magma Cap": "マグマタケ",
"Magma Geode": "マグマジオード",
"Magma Geode Stone": "マグマジオード鉱脈",
"Magnet": "マグネット",
"Magnet Ring": "磁石の指輪",
"Magnifying Glass": "虫眼鏡",
"Mahogany Bench": "マホガニーのベンチ",
"Mahogany Chair": "マホガニーのイス",
"Mahogany Dining Table": "マホガニーのダイニングテーブル",
"Mahogany Dresser": "マホガニーのタンス",
"Mahogany End Table": "マホガニーのサイドテーブル",
"Mahogany Lamp End Table": "マホガニー材のランプのサイドテーブル",
"Mahogany Seed": "マホガニーのタネ",
"Mahogany Table": "マホガニーのテーブル",
"Mahogany Tea-Table": "マホガニーのティーテーブル",
"Maki Roll": "巻きずし",
"Malachite": "マラカイト",
"Manager of the Year": "年間最優秀経営者",
"Mango": "マンゴー",
"Mango Sapling": "マンゴーの苗",
"Mango Sticky Rice": "マンゴーライス",
"Manicured Pine": "室内用イトスギ",
"Maple Bar": "メープルバー",
"Maple Seed": "カエデのタネ",
"Maple Syrup": "メープルシロップ",
"Mapping Cave Systems": "洞窟の地図",
"Marble": "大理石",
"Marble Brazier": "大理石のたき火台",
"Maru Portrait": "マルのポートレート",
"Maru's Wrench": "マルのレンチ",
"Master": "達人",
"Master Slingshot": "マスターパチンコ",
"Mayonnaise": "マヨネーズ",
"Mayonnaise Machine": "マヨネーズマシン",
"Mayoral Suspenders": "町長のサスペンダー",
"Mead": "はちみつ酒",
"Mega Bomb": "メガボム",
"Melon": "メロン",
"Melon Seeds": "メロンのタネ",
"Meowmere": "ミャオメア",
"Mermaid's Pendant": "人魚のペンダント",
"Messy Shirt": "汚れたシャツ",
"Messy Shorts": "散らかったパンツ",
"Metal Chair": "メタルチェア",
"Metal Window": "鉄の窓",
"Midnight Beach Bed": "ベッド",
"Midnight Beach Double Bed": "ダブルベッド",
"Midnight Carp": "シャイなコイ",
"Midnight Dog Jacket": "ミッドナイトドッグジャケット",
"Midnight Squid": "夜闇イカ",
"Milk": "ミルク",
"Milk Pail": "ミルクいれ",
"Miner's Crest": "鉱山労働者の紋章",
"Miner's Treat": "マインキャンディ",
"Mineral Dog Jacket": "ミネラルドッグジャケット",
"Mini-Forge": "小さな鍛造機",
"Mini-Fridge": "ミニ冷蔵庫",
"Mini-Jukebox": "ミニ・ジュークボックス",
"Mini-Obelisk": "ミニオベリスク",
"Mini-Shipping Bin": "ミニ出荷箱",
"Mining Monthly": "月刊マイニング",
"Mint Blouse": "ミントブラウス",
"Mixed Cane": "いろいろステッキ",
"Mixed Flower Seeds": "花のミックスシード",
"Mixed Seeds": "ミックスシード",
"Model Planes": "模型飛行機",
"Model Ship": "帆船の模型",
"Modern Bench": "モダンなベンチ",
"Modern Bookcase": "モダンな本棚",
"Modern Dining Table": "モダンなダイニングテーブル",
"Modern Double Bed": "モダンなダブルベッド",
"Modern End Table": "モダンなサイドテーブル",
"Modern Fish Tank": "モダンな水槽",
"Modern Lamp": "モダンなランプ",
"Modern Rug": "モダンなラグマット",
"Modern Table": "モダンなテーブル",
"Modern Tea-Table": "モダンなティーテーブル",
"Moldy Couch": "カビの生えたソファ",
"Monster Compendium": "モンスター図鑑",
"Monster Danglers": "つりさげモンスター",
"Monster Fireplace": "怪物暖炉",
"Monster Musk": "モンスターの香り",
"Monster Rug": "モンスターラグ",
"Moon Table": "月のテーブル",
"Moonlight Jellies Banner": "ゲッコウクラゲのバナー",
"Morel": "アミガサタケ",
"Morel Shirt": "モレルシャツ",
"Moss": "コケ",
"Moss Soup": "コケのスープ",
"Mossy Seed": "コケむしたタネ",
"Mounted Trout": "マスの飾り",
"Movie Ticket": "映画のチケット",
"Ms. Angler": "ミズ・ツリビトアンコウ",
"Mudstone": "泥岩",
"Mummified Bat": "コウモリのミイラ",
"Mummified Frog": "カエルのミイラ",
"Muscle Remedy": "パワーレメディ",
"Mushroom Box": "キノコボックス",
"Mushroom Log": "キノコの原木",
"Mushroom Tree Seed": "キノコの木のタネ",
"Mussel": "ムールガイ",
"Mussel Stone": "ムールガイ鉱脈",
"Must be planted indoors or on Ginger Island.": "室内かジンジャーアイランドにしか植えられない。",
"Mutant Carp": "ミュータントゴイ",
"My First Painting": "私の最初の絵",
"Mystery Box": "ミステリーボックス",
"Mystery Shirt": "ミステリーシャツ",
"Mystic Rug": "神秘的なラグマット",
"Mystic Stone": "神秘の鉱脈",
"Mystic Syrup": "神秘のシロップ",
"Mystic Tree Seed": "神秘の木のタネ",
"Napalm Ring": "ナパームリング",
"Nautical Rug": "海洋ラグ",
"Nautilus Fossil": "アンモナイトの化石",
"Nautilus Shell": "オウムガイの貝がら",
"Navy Tuxedo": "ネイビータキシード",
"Neat Bow Shirt": "ニートボウシャツ",
"Necklace Shirt": "ネックレスシャツ",
"Needlepoint Flower": "花の刺しゅう画",
"Nekoite": "ネコ石",
"Neolithic Table": "石器時代のテーブル",
"Neptune's Glaive": "ネプチューンのつるぎ",
"Neptunite": "海王石",
"Night Sky Decal #1": "ナイトスカイデカール＃1",
"Night Sky Decal #2": "ナイトスカイデカール＃2",
"Night Sky Decal #3": "ナイトスカイデカール＃3",
"Night Sky Shirt": "ナイトスカイシャツ",
"Oak Bench": "オーク材のベンチ",
"Oak Chair": "オーク材のイス",
"Oak Dresser": "オーク材のタンス",
"Oak End Table": "オーク材のサイドテーブル",
"Oak Lamp End Table": "オーク材のランプのサイドテーブル",
"Oak Resin": "オークの樹脂",
"Oak Table": "オーク材のテーブル",
"Oak Tea-Table": "オーク材のティーテーブル",
"Oasis Gown": "オアシスガウン",
"Obelisk": "オベリスク",
"Obsidian": "黒曜石",
"Obsidian Edge": "黒曜石の剣",
"Obsidian Vase": "黒曜石の花びん",
"Ocean Shirt": "オーシャンシャツ",
"Ocean Stone": "オーシャンストーン",
"Oceanic Rug": "海のラグ",
"Octopus": "タコ",
"Officer Uniform": "オフィスのユニフォーム",
"Oil": "オイル",
"Oil Maker": "オイルメーカー",
"Oil Stained Shirt": "油汚れの付いたシャツ",
"Oil of Garlic": "ガーリックオイル",
"Ol' Slitherlegs": "ベテランランナー",
"Old World Rug": "古典的なラグマット",
"Omelet": "オムレツ",
"Omni Geode": "オムニジオード",
"Omni Geode Stone": "オムニジオード鉱脈",
"Omni Shirt": "オムニシャツ",
"Only works in Cellar.": "地下室でしかつかえない。",
"Opal": "オパール",
"Orange": "オレンジ",
"Orange Bow Shirt": "オレンジボウシャツ",
"Orange Gi": "オレンジ着",
"Orange Office Stool": "オレンジのオフィススツール",
"Orange Sapling": "オレンジの苗",
"Orange Shirt": "オレンジシャツ",
"Orange Sleeping Junimo": "オレンジの眠ったジュニモ",
"Ornamental Fan": "かざり用の扇",
"Ornamental Hay Bale": "干し草俵",
"Ornate Lamp": "飾り付きのランプ",
"Ornate Necklace": "華やかなネックレス",
"Ornate Window": "飾り付きの窓",
"Orpiment": "オーピメント",
"Ossified Blade": "骨のつるぎ",
"Ostrich Egg": "ダチョウのタマゴ",
"Ostrich Incubator": "ダチョウふ卵器",
"Outlet": "コンセント",
"Oyster": "カキ",
"Pale Ale": "ペールエール",
"Pale Broth": "澄んだスープ",
"Palm Fossil": "ヤシの化石",
"Palm Wall Ornament": "ヤシの葉の壁飾り",
"Pancakes": "パンケーキ",
"Pants": "パンツ",
"Parsnip": "パースニップ",
"Parsnip Seeds": "パースニップのタネ",
"Parsnip Soup": "パースニップのスープ",
"Pastel Banner": "パステルカラーのバナー",
"Patchwork Rug": "パッチワークラグマット",
"Peach": "モモ",
"Peach Sapling": "モモの苗",
"Pearl": "しんじゅ",
"Pendant Shirt": "ペンダントシャツ",
"Penny Portrait": "ペニーのポートレート",
"Penny's Fryer": "ペニーのフライパン",
"Pepper Poppers": "揚げトウガラシ",
"Pepper Seeds": "トウガラシのタネ",
"Perch": "パーチ",
"Periodic Table": "周期表",
"Periwinkle": "タマキビ",
"Pet License": "ペットライセンス",
"Petrified Slime": "スライムの化石",
"Phoenix Ring": "フェニックスリング",
"Pickaxe": "ツルハシ",
"Pickles": "ピクルス",
"Pierre's Missing Stocklist": "ピエールの欠品在庫リスト",
"Pierre's Sign": "ピエールの看板",
"Pig Painting": "ブタの絵",
"Pike": "パイク",
"Pine Cone": "マツぼっくり",
"Pine Tar": "マツやに",
"Pineapple": "パイナップル",
"Pineapple Seeds": "パイナップルのタネ",
"Pink Cake": "ピンクケーキ",
"Pink Office Chair": "ピンクのオフィスチェア",
"Pink Plush Seat": "ピンクのふかふかシート",
"Pink Striped Shirt": "ピンクストライプシャツ",
"Pirate Double Bed": "海賊のダブルベッド",
"Pirate Flag": "海賊旗",
"Pirate Rug": "海賊ラグ",
"Pirate's Locket": "海賊のロケット",
"Pirate's Sword": "海賊の剣",
"Pizza": "ピザ",
"Piña Colada": "ピニャコラーダ",
"Plain Overalls": "無地のオーバーオール",
"Plain Shirt (F)": "無地のシャツ（女）",
"Plain Shirt (M)": "無地のシャツ（男）",
"Plain Torch": "普通のたいまつ",
"Plasma TV": "プラズマTV",
"Plastic Bag": "ビニール袋",
"Plastic Lawn Chair": "ガーデンチェア",
"Plastic Lawn End Table": "ガーデンサイドテーブル",
"Plastic Plant": "ビニールの鉢植え",
"Plastic Sapling": "ビニールの苗",
"Pleated Skirt": "プリーツスカート",
"Plum Pudding": "プラムのプディング",
"Plush Bunny": "ウサギのぬいぐるみ",
"Poi": "ポイ",
"Polka Dot Shirt": "ポルカドットシャツ",
"Polka Dot Shorts": "ポルカドットショーツ",
"Pomegranate": "ザクロ",
"Pomegranate Sapling": "ザクロの苗",
"Poppy": "ポピー",
"Poppy Seeds": "ポピーシード",
"Poppyseed Muffin": "ポピーシードマフィン",
"Porthole": "のぞき窓",
"Potato": "ジャガイモ",
"Potato Seeds": "ジャガイモのタネいも",
"Potted Red Mushroom": "赤キノコの鉢植え",
"Pour-Over Shirt": "ポアオーバーシャツ",
"Powdermelon": "パウダーメロン",
"Powdermelon Seeds": "パウダーメロンのタネ",
"Powerful": "パワフル",
"Prairie King Arcade System": "ゲーム機（プレーリーキング）",
"Prehistoric Handaxe": "有史前の手オノ",
"Prehistoric Rib": "有史前のろっ骨",
"Prehistoric Scapula": "有史前の肩甲骨",
"Prehistoric Skull": "有史前の頭がい骨",
"Prehistoric Tibia": "有史前のけい骨",
"Prehistoric Tool": "有史前のどうぐ",
"Prehistoric Vertebra": "有史前の脊椎",
"Preserves Jar": "保存ジャー",
"Preserving": "温存",
"Pressure Nozzle": "圧力ノズル",
"Price Catalogue": "値段表",
"Prismatic Genie Pants": "プリズムジニーパンツ",
"Prismatic Jelly": "プリズムゼリー",
"Prismatic Pants": "プリズムパンツ",
"Prismatic Shard": "レインボージェム",
"Prismatic Shirt": "プリズムシャツ",
"Prize Ticket": "賞品チケット",
"Protection Ring": "プロテクションリング",
"Pub Table": "酒場のテーブル",
"Pufferfish": "ハリセンボン",
"Pumpkin": "カボチャ",
"Pumpkin Pie": "パンプキンパイ",
"Pumpkin Seeds": "カボチャのタネ",
"Pumpkin Soup": "カボチャのスープ",
"Purple Blouse": "パープルブラウス",
"Purple Book": "紫の本",
"Purple Mushroom": "むらさきキノコ",
"Purple Office Chair": "むらさきのオフィスチェア",
"Purple Serpent Statue": "紫の蛇の像",
"Purple Sleeping Junimo": "紫の眠ったジュニモ",
"Purple Slime Egg": "パープルスライムのタマゴ",
"Puzzle Table": "パズルテーブル",
"Pyramid Decal": "ピラミッドステッカー",
"Pyrite": "パイライト",
"Qi Bean": "Qiビーン",
"Qi Fruit": "Qiフルーツ",
"Qi Gem": "Qiジェム",
"Qi Seasoning": "Qi調味料",
"Quality Bobber": "上質なウキ",
"Quality Fertilizer": "高級な肥料",
"Quality Retaining Soil": "高級な保水土",
"Quality Sprinkler": "高品質スプリンクラー",
"Quartz": "水晶",
"Queen Of Sauce Cookbook": "ソースの女王の料理本",
"Rabbit's Foot": "ウサギの足",
"Raccoon Journal": "アライグマ新聞",
"Radio Desk": "無線用の机",
"Radioactive Bar": "放射性ののべ棒",
"Radioactive Carp": "放射性コイ",
"Radioactive Ore": "放射性の鉱石",
"Radioactive Stone": "放射性鉱脈",
"Radish": "ラディッシュ",
"Radish Salad": "ラディッシュサラダ",
"Radish Seeds": "ラディッシュのタネ",
"Rain Coat": "レインコート",
"Rain Totem": "レイントーテム",
"Rainbow Shell": "レインボーシェル",
"Rainbow Trout": "ニジマス",
"Raisins": "干しブドウ",
"Ranger Uniform": "レンジャーユニフォーム",
"Rapier": "レイピア",
"Rare Disc": "貴重な円盤",
"Rare Seed": "珍しいタネ",
"Rarecrow": "レアなカカシ",
"Reaching": "開放的",
"Recycling Machine": "リサイクルマシン",
"Red Armchair": "レッドのひじかけイス",
"Red Book": "赤い本",
"Red Buttoned Vest": "レッドボタン付きベスト",
"Red Cabbage": "赤キャベツ",
"Red Cabbage Seeds": "赤キャベツのタネ",
"Red Canes": "レッドステッキ（小）",
"Red Cottage Rug": "赤いコテージラグマット",
"Red Couch": "レッドソファ",
"Red Cushion": "赤いクッション",
"Red Diner Chair": "赤いダイナーチェア",
"Red Flannel Shirt": "レッドフランネルシャツ",
"Red Hoodie": "レッドのパーカー",
"Red Mullet": "ウミヒゴイ",
"Red Mushroom": "赤キノコ",
"Red Plate": "レッドサラダ",
"Red Rug": "赤いラグマット",
"Red Sleeping Junimo": "赤い眠ったジュニモ",
"Red Slime Egg": "レッドスライムのタマゴ",
"Red Snapper": "フエダイ",
"Red Striped Shirt": "レッドストライプシャツ",
"Red Tuxedo": "レッドタキシード",
"Refined Quartz": "精錬クリスタル",
"Regal Mantle": "リーガルマントル",
"Relaxed Fit Pants": "リラックスフィットパンツ",
"Relaxed Fit Shorts": "リラックスフィットショーツ",
"Relic Shirt": "レリックシャツ",
"Retro Banner": "レトロなバナー",
"Retro Bed": "レトロなベッド",
"Retro Bookcase": "レトロな本棚",
"Retro Cabinet": "レトロなキャビネット",
"Retro Catalogue": "レトロカタログ",
"Retro Chair": "レトロなイス",
"Retro Couch": "レトロなソファ",
"Retro Cushion": "レトロなクッション",
"Retro Dresser": "レトロなタンス",
"Retro End Table": "レトロなサイドテーブル",
"Retro Fireplace": "レトロな暖炉",
"Retro Flower": "レトロな花",
"Retro Lamp": "レトロなランプ",
"Retro Mat": "レトロなマット",
"Retro Plant": "レトロな植物",
"Retro Radio": "レトロなラジオ",
"Retro Rainbow Shirt": "レトロレインボーシャツ",
"Retro Rug": "レトロなラグ",
"Retro Square Rug": "四角いレトロなラグ",
"Retro Stool": "レトロなスツール",
"Retro TV": "レトロなテレビ",
"Retro Table": "レトロなテーブル",
"Retro Tea Table": "レトロなティーテーブル",
"Return Scepter": "帰還の杖",
"Rhubarb": "ルバーブ",
"Rhubarb Pie": "ルバーブのパイ",
"Rhubarb Seeds": "ルバーブのタネ",
"Rice": "米",
"Rice Pudding": "ライスプディング",
"Rice Shoot": "稲芽",
"Ring of Yoba": "ヨバ神の指輪",
"Ritual Mask": "儀式用マスク",
"River Jelly": "川ゼリー",
"Roasted Hazelnuts": "焼きヘーゼルナッツ",
"Roe": "魚卵",
"Roots Platter": "根菜盛り",
"Rotten Plant": "くさった植物",
"Ruby": "ルビー",
"Ruby Crystal Ball": "ルビーの水晶玉",
"Ruby Ring": "ルビーの指輪",
"Ruby Stone": "ルビー鉱脈",
"Rune Rug": "ルーン文字のラグ",
"Rustic Plank Floor": "素朴な厚板の床",
"Rusty Cog": "サビた歯車",
"Rusty Shirt": "さびの付いたシャツ",
"Rusty Spoon": "サビたスプーン",
"Rusty Spur": "サビた拍車",
"Rusty Sword": "サビた剣",
"S. Pine": "小さなマツの木",
"S. Wall Flower": "小さな壁掛けのヒマワリ",
"Sailor Shirt": "セーラーシャツ",
"Salad": "サラダ",
"Salmon": "サケ",
"Salmon Dinner": "サーモンディナー",
"Salmonberry": "サーモンベリー",
"Sam Portrait": "サムのポートレート",
"Sam's Boombox": "サムのブームボックス",
"Sam's Old Guitar": "サムの古いギター",
"Sam's Skateboard": "サムのスケボー",
"Sandfish": "スナゴチ",
"Sandstone": "砂岩",
"Sandy Rug": "サンディのラグ",
"Sap": "樹液",
"Sardine": "イワシ",
"Sashimi": "刺し身",
"Sauce-Stained Shirt": "ソースステインシャツ",
"Savage Ring": "野生の指輪",
"Scarecrow": "カカシ",
"Scorpion Carp": "サソリゴイ",
"Scythe": "カマ",
"Sea Cucumber": "ナマコ",
"Sea Jelly": "海ゼリー",
"Sea Urchin": "ウニ",
"Seafoam Pudding": "海の泡プリン",
"Seasonal Decor": "季節の飾り",
"Seasonal Plant": "シーズンプラント",
"Seaweed": "海草",
"Seb's Lost Mace": "セバスチャンのメイス",
"Sebastian Portrait": "セバスチャンのポートレート",
"Secret Note": "ひみつのメモ",
"Seed Maker": "タネ製造マシン",
"Sewing Machine": "ミシン",
"Shad": "アロサ",
"Shadow Dagger": "シャドウダガー",
"Shane Portrait": "シェーンのポートレート",
"Shaving": "シェービング",
"Shears": "大ハサミ",
"Shirt": "シャツ",
"Shirt And Belt": "シャツとベルト",
"Shirt And Tie": "シャツとネクタイ",
"Shirt O' The Sea": "シャツ・オ・ザ・シー",
"Shirt with Bow": "ボー付きシャツ",
"Short Bookcase": "低い本棚",
"Short Jacket": "ショートジャケット",
"Short Wizard Bookcase": "低い魔術師の本棚",
"Shorts": "ショーツ",
"Shrimp": "エビ",
"Shrimp Cocktail": "エビのカクテル",
"Shrimp Enthusiast Shirt": "エビ愛好家のシャツ",
"Sign Of The Vessel": "船舶の象徴",
"Silky Shirt": "シルクシャツ",
"Silver Saber": "銀のサーベル",
"Simple Dress": "シンプルドレス",
"Singing Stone": "ソングストーン",
"Six-Pack Rings": "6缶パックリング",
"Skeletal Hand": "手のホネ",
"Skeletal Tail": "しっぽのホネ",
"Skeleton": "骨格標本",
"Skeleton Model": "スケルトンの模型",
"Skeleton Shirt": "スケルトンシャツ",
"Skirt": "スカート",
"Skull Brazier": "ドクロのたき火台",
"Skull Poster": "ドクロのポスター",
"Skull Shirt": "スカルシャツ",
"Slate": "スレート",
"Sleeveless Overalls": "ノースリーブのオーバーオール",
"Slime": "スライム",
"Slime Ball": "スライムボール",
"Slime Charmer Ring": "スライムチャームリング",
"Slime Crate": "スライムの木枠",
"Slime Egg-Press": "スライムエッグプレス",
"Slime Incubator": "スライム用ふ卵器",
"Slime Shirt": "スライムシャツ",
"Slimejack": "スライムジャック",
"Slingshot": "パチンコ",
"Sloth Skeleton L": "ナマケモノの化石 L",
"Sloth Skeleton M": "ナマケモノの化石 M",
"Sloth Skeleton R": "ナマケモノの化石 R",
"Small Book Pile": "小さな本の山",
"Small Book Stack": "小さな本の積み重ね",
"Small Crystal": "小さなクリスタル",
"Small Elixir Shelf": "小さなエリクサーの棚",
"Small Fish Tank": "小さな水槽",
"Small Glow Ring": "光の指輪S",
"Small Joja Rug": "小さなJajaのラグ",
"Small Junimo Hut": "小さなジュニモの小屋",
"Small Junimo Mat": "小さなジュニモのマット",
"Small Junimo Plush": "スモールジュニモぬいぐるみ",
"Small Junimo Pot": "小さなジュニモのつぼ",
"Small Magnet Ring": "磁石の指輪S",
"Small Plant": "小さな鉢植え",
"Small Stacked Elixir Shelf": "小さなエリクサーの棚の積み重ね",
"Small Wall Pumpkin": "小さなウォールパンプキン",
"Small Window": "小さな窓",
"Small Wizard Bookcase": "小さな魔術師の本棚",
"Smallmouth Bass": "コクチバス",
"Smoked": "くんせい",
"Smoked Fish": "魚のくんせい",
"Snail": "カタツムリ",
"Snake Skull": "ヘビの頭がい骨",
"Snake Vertebrae": "ヘビの背骨",
"Snow Yam": "スノーヤム",
"Snowy Rug": "スノーウィーラグ",
"Snowy Stone": "雪鉱脈",
"Soapstone": "ソープストーン",
"Soda Machine": "コーラマシン",
"Soft Arrow Shirt": "ソフトアローシャツ",
"Soggy Newspaper": "ふやけた新聞紙",
"Solar Essence": "光の結晶",
"Solar Panel": "ソーラーパネル",
"Solid Gold Lewis": "ルイスの黄金像",
"Son of Crimsonfish": "クリムゾンフィッシュの息子",
"Sonar Bobber": "探知ウキ",
"Soul Sapper Ring": "ソウルサッパーリング",
"Spaghetti": "スパゲッティ",
"Spangle Seeds": "スパングルのタネ",
"Special Charm": "特別な飾り",
"Speed-Gro": "グングンノビール",
"Spice Berry": "スパイスベリー",
"Spicy Eel": "ピリ辛ウナギ",
"Spilled Beverage": "こぼれた飲み物",
"Spinner": "スピナー",
"Spirit Torch": "精霊のたいまつ",
"Spirits Table": "蒸留酒テーブル",
"Spook Fish": "ぶきみ魚",
"Sports Shirt": "スポーツシャツ",
"Spring Onion": "葉タマネギ",
"Spring Onion Mastery": "葉タマネギマスター",
"Spring Seeds": "春のタネつめあわせ",
"Spring Shirt": "スプリングシャツ",
"Sprinkler": "スプリンクラー",
"Square Joja Rug": "四角いJajaのラグ",
"Square Junimo Rug": "四角いジュニモのラグ",
"Squid": "イカ",
"Squid Ink": "イカのインク",
"Squid Ink Ravioli": "イカスミのラビオリ",
"Squirrel Figurine": "リスの像",
"Stacked Elixir Shelf": "エリクサーの棚の積み重ね",
"Stacked Joja Boxes": "Jojaの箱の積み重ね",
"Staircase": "階段",
"Standing Geode": "晶洞石のおきもの",
"Star Shards": "星のかけら",
"Star Shirt": "スターシャツ",
"Starburst": "星形",
"Stardew Hero Trophy": "スターデューヒーロートロフィー",
"Stardew Valley Almanac": "スターデューバレー年鑑",
"Stardew Valley Rose": "スターデューバレーのバラ",
"Stardrop": "スタードロップ",
"Stardrop Tea": "スタードロップティー",
"Starfruit": "スターフルーツ",
"Starfruit Seeds": "スターフルーツのタネ",
"Starport Decal": "星空の窓のステッカー",
"Starry Double Bed": "星降るダブルベッド",
"Starry Moon Rug": "星月夜のラグ",
"Statue Of Blessings": "祝福の像",
"Statue Of Endless Fortune": "おわりなき幸運の像",
"Statue Of Perfection": "完全無欠の像",
"Statue Of The Dwarf King": "ドワーフキングの像",
"Statue Of True Perfection": "真の完璧の像",
"Steel Axe": "鋼のオノ",
"Steel Breastplate": "スチール製ブレストプレート",
"Steel Falchion": "ファルシオン",
"Steel Hoe": "鋼のクワ",
"Steel Pan": "鋼の砂金皿",
"Steel Pickaxe": "鋼のツルハシ",
"Steel Smallsword": "鋼鉄の片手剣",
"Steel Trash Can": "鋼のゴミ箱",
"Steel Watering Can": "鋼のジョウロ",
"Stepping Stone Path": "跳び石の小道",
"Stingray": "エイ",
"Stir Fry": "野菜いため",
"Stone": "石",
"Stone Base": "石の土台",
"Stone Brazier": "石のたき火台",
"Stone Cairn": "石のケアン",
"Stone Chest": "石の箱",
"Stone Fence": "石の柵",
"Stone Fireplace": "石の暖炉",
"Stone Floor": "石の床",
"Stone Flooring": "石のフローリング",
"Stone Frog": "石のカエル",
"Stone Junimo": "石のジュニモ",
"Stone Owl": "石のフクロウ",
"Stone Parrot": "石のオウム",
"Stone Sign": "石の掲示板",
"Stone Slab": "ぶあつい石板",
"Stone Walkway Floor": "石畳の床",
"Stonefish": "ダルマオコゼ",
"Store Owner's Jacket": "店主のジャケット",
"Stove Fireplace": "ストーブ",
"Strange Bun": "おかしなパン",
"Strange Capsule": "奇妙なカプセル",
"Strange Doll": "奇妙な人形",
"Strapped Top": "ストラップ付きトップス",
"Straw Floor": "ワラの床",
"Strawberry": "イチゴ",
"Strawberry Decal": "ストロベリーデカール",
"Strawberry Double Bed": "イチゴのダブルベッド",
"Strawberry Seeds": "イチゴのタネ",
"Striped Shirt": "ストライプシャツ",
"Studded Vest": "スタッド付きベスト",
"Stuffing": "肉づめ",
"Stump Brazier": "丸太のたき火台",
"Stump Seat": "切りかぶの腰かけ",
"Stump Torch": "切り株のたいまつ",
"Sturdy Ring": "鉄壁の指輪",
"Sturgeon": "チョウザメ",
"Sugar": "砂糖",
"Sugar Shirt": "シュガーシャツ",
"Suit Of Armor": "よろい一式",
"Suit Top": "スーツトップス",
"Summer Seeds": "夏のタネつめあわせ",
"Summer Spangle": "サマースパングル",
"Summer Squash": "サマースクワッシュ",
"Summer Squash Seeds": "サマースクワッシュのタネ",
"Sun Dunes": "太陽の砂丘",
"Sun Table": "太陽のテーブル",
"Sunfish": "ブルーギル",
"Sunflower": "ヒマワリ",
"Sunflower Seeds": "ヒマワリのタネ",
"Sunset Shirt": "サンセットシャツ",
"Super Cucumber": "スーパーナマコ",
"Super Meal": "パワフルいため",
"SupplyCrate": "供給木枠",
"Survival Burger": "サバイバルバーガー",
"Swamp Plant": "沼地の植物",
"Sweet Gem Berry": "スイートジェムベリー",
"Sweet Pea": "スイートピー",
"Swift": "俊敏",
"Swirl Rug": "渦巻きのラグ",
"Table Piece L": "テーブルパーツL",
"Table Piece R": "テーブルパーツR",
"Table Plant": "卓上鉢植え",
"Tall House Plant": "背の高い観葉植物",
"Tall Torch": "ロングトーチ",
"Tan Striped Shirt": "褐色のストライプシャツ",
"Tank Top (F)": "タンクトップ（女）",
"Tank Top (M)": "タンクトップ（男）",
"Tapper": "樹液採取器",
"Taro Root": "タロイモの根",
"Taro Tuber": "タロイモのタネいも",
"Tea Leaves": "茶葉",
"Tea Sapling": "茶の苗木",
"Tea Set": "ティーセット",
"Tea Shirt": "おチャツ",
"Teddy Timer": "クマちゃんの時計",
"Telephone": "電話",
"Tempered Broadsword": "精鍛の剣",
"Templar's Blade": "騎士のつるぎ",
"Tent Kit": "テントキット",
"Text Sign": "看板",
"The Alleyway Buffet": "路地裏のビュッフェ",
"The Art O' Crabbing": "カニの学問",
"The Diamond Hunter": "ダイヤモンドハンター",
"The Slammer": "グランドハンマー",
"This package belongs to someone else.": "この小包は他の人のもののようだ",
"Thorns Ring": "トゲの指輪",
"Thunder Egg": "サンダーエッグ",
"Tie Dye Shirt": "染め物のシャツ",
"Tiger Slime Egg": "タイガースライムのタマゴ",
"Tiger Trout": "タイガートラウト",
"Tigerseye": "タイガーアイ",
"Tight Pants": "タイトパンツ",
"Tilapia": "ティラピア",
"Tire": "タイヤ",
"Toasted Shirt": "トーストシャツ",
"Toga Shirt": "トーガシャツ",
"Tom Kha Soup": "トムカーガイ",
"Tomato": "トマト",
"Tomato Seeds": "トマトのタネ",
"Tomato Shirt": "トマトシャツ",
"Topaz": "トパーズ",
"Topaz Crystal Ball": "トパーズの水晶玉",
"Topaz Ring": "トパーズの指輪",
"Topaz Stone": "トパーズ鉱脈",
"Topiary Tree": "トピアリー",
"Torch": "たいまつ",
"Tortilla": "トルティーヤ",
"Tortilla Shirt": "トルティーヤシャツ",
"Totem Pole": "トーテムポール",
"Track Jacket": "トラックジャケット",
"Training Rod": "練習用の釣竿",
"Transmute (Au)": "変化（金）",
"Transmute (Fe)": "変化（鉄）",
"Trap Bobber": "しかけウキ",
"Trash": "ゴミ",
"Trash Can": "ゴミ箱",
"Trash Can Shirt": "ゴミ箱シャツ",
"Trash Catalogue": "ゴミカタログ",
"Treasure Appraisal Guide": "古代の秘宝鑑定ガイド",
"Treasure Chest": "宝箱",
"Treasure Hunter": "お宝キャッチャー",
"Treasure Totem": "宝のトーテム",
"Tree Column": "木の柱",
"Tree Fertilizer": "木の肥料",
"Tree of the Winter Star": "冬星祭のツリー",
"Triangle Window": "三角窓",
"Trilobite": "三葉虫",
"Trimmed Lucky Purple Shorts": "ラッキーパープルショートパンツ",
"Trinket Shirt": "トリンケットシャツ",
"Triple Shot Espresso": "トリプルショットエスプレッソ",
"Tropical Bed": "トロピカルベッド",
"Tropical Chair": "トロピカルチェア",
"Tropical Curry": "トロピカルカレー",
"Tropical Double Bed": "トロピカルダブルベッド",
"Tropical Sunrise Shirt": "トロピカルサンライズシャツ",
"Tropical TV": "トロピカルTV",
"Trout Soup": "マスのスープ",
"Truffle": "トリュフ",
"Truffle Oil": "トリュフオイル",
"Tub o' Flowers": "タルフラワー",
"Tube Top": "チューブトップ",
"Tulip": "チューリップ",
"Tulip Bulb": "チューリップの球根",
"Tuna": "マグロ",
"Tunnelers Jersey": "トンネルジャージ",
"Turtleneck Sweater": "タートルネックセーター",
"Twig": "小枝",
"Two Elixirs": "2つのエリクサー",
"Unmilled Rice": "玄米",
"Upright Piano": "アップライトピアノ",
"Vacation Shirt": "バケーションシャツ",
"Vampire Ring": "ヴァンパイアの指輪",
"Vampiric": "吸血鬼",
"Vegetable Medley": "野菜のシチュー",
"Vinegar": "酢",
"Vintage Polo": "ビンテージポロ",
"Void Egg": "ヴォイドエッグ",
"Void Essence": "闇の結晶",
"Void Ghost Pendant": "ボイドゴーストペンダント",
"Void Mayonnaise": "ヴォイドマヨネーズ",
"Void Salmon": "闇サーモン",
"Wall Basket": "壁掛けバスケット",
"Wall Cactus": "サボテンのステッカー",
"Wall Clock": "壁掛け時計",
"Wall Flower": "壁掛けのヒマワリ",
"Wall Palm": "ヤシの木のステッカー",
"Wall Pumpkin": "ウォールパンプキン",
"Wall Sconce": "壁掛け燭台",
"Wall Sword": "壁掛けの剣",
"Walleye": "ウォールアイ",
"Wallflower Pal": "ウォールフレンド",
"Walnut Bench": "クルミ材のベンチ",
"Walnut Chair": "クルミ材のイス",
"Walnut Dresser": "クルミ材のタンス",
"Walnut End Table": "クルミ材のサイドテーブル",
"Walnut Lamp End Table": "クルミ材のランプのサイドテーブル",
"Walnut Table": "クルミ材のテーブル",
"Walnut Tea-Table": "クルミ材のティーテーブル",
"War Memento": "戦争の思い出",
"Warm Flannel Shirt": "ワームフランネルシャツ",
"Warp Totem: Beach": "ワープトーテム：浜辺",
"Warp Totem: Desert": "ワープトーテム：砂漠",
"Warp Totem: Farm": "ワープトーテム：牧場",
"Warp Totem: Island": "ワープトーテム：アイランド",
"Warp Totem: Mountains": "ワープトーテム：山",
"Warp Totem: Qi's Arena": "ワープトーテム：Qiアリーナ",
"Warrior Ring": "戦士の指輪",
"Water Pet Bowl": "ペット用ウォーターボウル",
"Watering Can": "ジョウロ",
"Way Of The Wind pt. 1": "風の道 パート1",
"Way Of The Wind pt. 2": "風の道 パート2",
"Weathered Floor": "古びた床",
"Wedding Ring": "結婚指輪",
"Weeds": "雑草",
"Wheat": "コムギ",
"Wheat Flour": "コムギ粉",
"Wheat Seeds": "コムギのタネ",
"White Algae": "白い藻",
"White Dot Shirt": "ホワイトドットシャツ",
"White Gi": "ホワイト着",
"White Overalls": "ホワイトオーバーオール",
"White Overalls Shirt": "ホワイトオーバーオールシャツ",
"Wicked Kris": "魔性のクリス",
"Wicked Statue": "邪悪な像",
"Wild Bait": "ワイルドな釣りエサ",
"Wild Double Bed": "野生のダブルベッド",
"Wild Honey": "百花ミツ",
"Wild Horseradish": "ノワサビ",
"Wild Plum": "野生のプラム",
"Wild Seeds (Fa)": "野生のタネ （秋）",
"Wild Seeds (Sp)": "野生のタネ （春）",
"Wild Seeds (Su)": "野生のタネ （夏）",
"Wild Seeds (Wi)": "野生のタネ （冬）",
"Wilted Bouquet": "しおれた花束",
"Wind Spire": "風のスピア",
"Wine": "ワイン",
"Wine Table": "ワインテーブル",
"Winter Banner": "冬のバナー",
"Winter Chair": "ウィンターチェア",
"Winter Dining Table": "ウィンターダイニングテーブル",
"Winter End Table": "ウィンターサイドテーブル",
"Winter Root": "クワイ",
"Winter Seeds": "冬のタネつめあわせ",
"Winter Table": "ウィンターテーブル",
"Winter Tree Decal": "ウィンターツリーデカール",
"Witch's Broom": "魔女のホウキ",
"Wizard Bed": "魔術師のベッド",
"Wizard Bookcase": "魔術師の本棚",
"Wizard Bookshelf": "魔術師のブックシェルフ",
"Wizard Catalogue": "魔術師カタログ",
"Wizard Chair": "魔術師のイス",
"Wizard Couch": "魔術師のソファ",
"Wizard Cushion": "魔術師のクッション",
"Wizard Dresser": "魔術師のタンス",
"Wizard End Table": "魔術師のサイドテーブル",
"Wizard Fireplace": "魔術師の暖炉",
"Wizard Lamp": "魔術師のランプ",
"Wizard Stool": "魔術師のスツール",
"Wizard Study": "魔術師の研究机",
"Wizard Table": "魔術師のテーブル",
"Wizard Tea Table": "魔術師のティーテーブル",
"Wood": "木材",
"Wood Chair": "木のイス",
"Wood Chipper": "ウッドチッパー",
"Wood Club": "木のこんぼう",
"Wood Fence": "木の柵",
"Wood Floor": "木の床",
"Wood Lamp-post": "木の街灯",
"Wood Mallet": "木のハンマー",
"Wood Panel": "木製の壁パネル",
"Wood Path": "木の小道",
"Wood Sign": "木の掲示板",
"Woodcut Rug": "木版ラグ",
"Woodcutter's Weekly": "週刊ウッドカッター",
"Wooden Blade": "木の剣",
"Wooden Brazier": "木のたき火台",
"Woodskip": "キノボリウオ",
"Woodsy Couch": "森のソファ",
"Woody's Secret": "ウッディの秘密",
"Wool": "ウール",
"Work Shirt": "作業用シャツ",
"Workbench": "作業台",
"World Map": "世界地図",
"Worm Bin": "ミミズ飼育器",
"Wrapper": "包み紙",
"Wriggling Worm": "くねくね虫",
"Wumbus Shirt": "ウンバスシャツ",
"Wumbus Statue": "ウンバス像",
"Yam": "サツマイモ",
"Yam Seeds": "サツマイモのタネいも",
"Yellow Armchair": "イエローのひじかけイス",
"Yellow Book": "黄色い本",
"Yellow Couch": "イエローソファ",
"Yellow Cushion": "黄色いクッション",
"Yellow Sleeping Junimo": "黄色い眠ったジュニモ",
"Yellow Suit": "イエロースーツ",
"Yellow and Green Shirt": "イエローアンドグリーンシャツ",
"Yeti Tooth": "イエティのキバ",
"Yoba Shirt": "ヨーバシャツ",
};
